
export const NEW_AGENTSORDER_REQUEST = "NEW_AGENTSORDER_REQUEST"
export const NEW_AGENTSORDER_SUCCESS = "NEW_AGENTSORDER_SUCCESS"
export const NEW_AGENTSORDER_FAIL = "NEW_AGENTSORDER_FAIL"


export const ALL_AGENTSORDER_REQUEST = "ALL_AGENTSORDER_REQUEST"
export const ALL_AGENTSORDER_SUCCESS = "ALL_AGENTSORDER_SUCCESS"
export const ALL_AGENTSORDER_FAIL = "ALL_AGENTSORDER_FAIL"



export const DELETE_AGENTSORDER_REQUEST = "DELETE_AGENTSORDER_REQUEST"
export const DELETE_AGENTSORDER_SUCCESS = "DELETE_AGENTSORDER_SUCCESS"
export const DELETE_AGENTSORDER_RESET = "DELETE_AGENTSORDER_RESET"
export const DELETE_AGENTSORDER_FAIL = "DELETE_AGENTSORDER_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERROR"