
export const NEW_FORM_REQUEST = "NEW_FORM_REQUEST"
export const NEW_FORM_SUCCESS = "NEW_FORM_SUCCESS"
export const NEW_FORM_FAIL = "NEW_FORM_FAIL"


export const ALL_FROM_REQUEST = "ALL_FROM_REQUEST"
export const ALL_FROM_SUCCESS = "ALL_FROM_SUCCESS"
export const ALL_FROM_FAIL = "ALL_FROM_FAIL"



export const DELETE_FORM_REQUEST = "DELETE_FORM_REQUEST"
export const DELETE_FORM_SUCCESS = "DELETE_FORM_SUCCESS"
export const DELETE_FORM_RESET = "DELETE_FORM_RESET"
export const DELETE_FORM_FAIL = "DELETE_FORM_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERROR"