export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"


export const MY_0RDERS_REQUEST = "MY_0RDERS_REQUEST"
export const MY_0RDERS_SUCCESS = "MY_0RDERS_SUCCESS"
export const MY_0RDERS_FAIL = "MY_0RDERS_FAIL"



export const ALL_0RDERS_REQUEST = "ALL_0RDERS_REQUEST"
export const ALL_0RDERS_SUCCESS = "ALL_0RDERS_SUCCESS"
export const ALL_0RDERS_FAIL = "ALL_0RDERS_FAIL"


export const UPDATE_0RDERS_REQUEST = "UPDATE_0RDERS_REQUEST"
export const UPDATE_0RDERS_SUCCESS = "UPDATE_0RDERS_SUCCESS"
export const UPDATE_0RDERS_RESET = "UPDATE_0RDERS_RESET"
export const UPDATE_0RDERS_FAIL = "UPDATE_0RDERS_FAIL"


export const DELETE_0RDERS_REQUEST = "DELETE_0RDERS_REQUEST"
export const DELETE_0RDERS_SUCCESS = "DELETE_0RDERS_SUCCESS"
export const DELETE_0RDERS_RESET = "DELETE_0RDERS_RESET"
export const DELETE_0RDERS_FAIL = "DELETE_0RDERS_FAIL"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERROR"