export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST"
export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCTS_SUCCESS"
export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCTS_FAIL"


export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"


export const PRODUCTS_DETAILS_REQUEST = "PRODUCTS_DETAILS_REQUEST"
export const PRODUCTS_DETAILS_SUCCESS = "PRODUCTS_DETAILS_SUCCESS"
export const PRODUCTS_DETAILS_FAIL = "PRODUCTS_DETAILS_FAIL"


export const NEW_PRODUCTS_REQUEST = "NEW_PRODUCTS_REQUEST"
export const NEW_PRODUCTS_SUCCESS = "NEW_PRODUCTS_SUCCESS"
export const NEW_PRODUCTS_RESET = "NEW_PRODUCTS_RESET"
export const NEW_PRODUCTS_FAIL = "NEW_PRODUCTS_FAIL"


export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST"
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS"
export const DELETE_PRODUCTS_RESET = "DELETE_PRODUCTS_RESET"
export const DELETE_PRODUCTS_FAIL = "DELETE_PRODUCTS_FAIL"

export const UPDATE_PRODUCTS_REQUEST = "UPDATE_PRODUCTS_REQUEST"
export const UPDATE_PRODUCTS_SUCCESS = "UPDATE_PRODUCTS_SUCCESS"
export const UPDATE_PRODUCTS_RESET = "UPDATE_PRODUCTS_RESET"
export const UPDATE_PRODUCTS_FAIL = "UPDATE_PRODUCTS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERROR"


